name: SARS-CoV-2-RBD_MAP
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - aioeasywebdav=2.4.0=py37_1000
  - aiohttp=3.6.2=py37h516909a_0
  - altair=4.1.0=py_1
  - appdirs=1.4.3=py_1
  - argon2-cffi=20.1.0=py37h8f50634_1
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - bcrypt=3.2.0=py37h8f50634_0
  - bleach=3.2.1=pyh9f0ad1d_0
  - boto3=1.15.0=pyh9f0ad1d_0
  - botocore=1.18.0=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37h8f50634_1000
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2020.6.20=hecda079_0
  - cachetools=4.1.1=py_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py37hc8dfbb8_0
  - cffi=1.14.3=py37h2b28604_0
  - chardet=3.0.4=py37hc8dfbb8_1007
  - colorama=0.4.3=py_0
  - configargparse=1.2.3=pyh9f0ad1d_0
  - cryptography=3.1=py37hb09aad4_0
  - curl=7.71.1=he644dc0_6
  - datrie=0.8.2=py37h8f50634_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.16=py37hc8dfbb8_1
  - dropbox=10.4.1=pyh9f0ad1d_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - expat=2.2.9=he1b5a44_2
  - fftw=3.3.8=nompi_h7f3a6c3_1111
  - filechunkio=1.8=py_2
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - ftputil=4.0.0=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - ghostscript=9.18=1
  - giflib=5.1.9=h516909a_0
  - git-lfs=2.11.0=0
  - gitdb=4.0.5=py_0
  - gitpython=3.1.8=py_0
  - glib=2.66.0=h0dae87d_0
  - google-api-core=1.22.2=py37hc8dfbb8_0
  - google-api-python-client=1.12.1=pyh9f0ad1d_0
  - google-auth=1.21.2=py_0
  - google-auth-httplib2=0.0.3=py_3
  - google-cloud-core=1.3.0=py_0
  - google-cloud-storage=1.30.0=pyh9f0ad1d_0
  - google-crc32c=1.0.0=py37h193935f_0
  - google-resumable-media=1.0.0=pyh9f0ad1d_0
  - googleapis-common-protos=1.51.0=py37hc8dfbb8_2
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.38.0=hf68f40c_1011
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.7.2=hee91db6_0
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - httplib2=0.18.1=pyh9f0ad1d_0
  - icu=67.1=he1b5a44_0
  - idna=2.10=pyh9f0ad1d_0
  - imagemagick=7.0.8_11=pl526hc610aec_0
  - importlib-metadata=1.7.0=py37hc8dfbb8_0
  - importlib_metadata=1.7.0=0
  - ipykernel=5.3.4=py37h43977f1_0
  - ipython=7.18.1=py37hc6149b9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=pyh9f0ad1d_1
  - jbig=2.1=h516909a_2002
  - jedi=0.17.2=py37hc8dfbb8_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - json5=0.9.4=pyh9f0ad1d_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py37_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - jupyter_highlight_selected_word=0.2.0=py37_1000
  - jupyter_latex_envs=1.4.6=py37_1000
  - jupyter_nbextensions_configurator=0.4.1=py37hc8dfbb8_1
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.1=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - jupytext=1.6.0=pyh9f0ad1d_0
  - krb5=1.17.1=hfafb76e_3
  - ld_impl_linux-64=2.35=h769bd43_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=10.0.1=default_hde54327_1
  - libcrc32c=1.1.1=he1b5a44_2
  - libcurl=7.71.1=hcdd3856_6
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_2
  - libffi=3.2.1=he1b5a44_1007
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.3.0=h24d8f2e_16
  - libgfortran-ng=7.5.0=hdf63c60_16
  - libgomp=9.3.0=h24d8f2e_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libpq=12.3=h5513abc_0
  - libprotobuf=3.13.0=h8b12597_0
  - libsodium=1.0.18=h516909a_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_16
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h516909a_1005
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.39.0=h516909a_0
  - libwebp=0.5.2=7
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=h68273f3_2
  - libxslt=1.1.33=h572872d_1
  - lxml=4.5.2=py37he3881c9_0
  - lz4-c=1.9.2=he1b5a44_3
  - mafft=7.471=h516909a_0
  - markdown-it-py=0.5.5=py_0
  - markupsafe=1.1.1=py37h8f50634_1
  - mistune=0.8.4=py37h8f50634_1001
  - multidict=4.7.5=py37h8f50634_1
  - mysql-common=8.0.21=2
  - mysql-libs=8.0.21=hf3661c5_2
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.3=py37hc8dfbb8_0
  - nbdime=2.0.0=py_1
  - nbformat=5.0.7=py_0
  - ncbi-ngs-sdk=2.10.4=h3e72335_1
  - ncurses=6.2=he1b5a44_1
  - nest-asyncio=1.4.0=py_0
  - networkx=2.5=py_0
  - nodejs=14.11.0=h568c755_0
  - notebook=6.1.4=py37hc8dfbb8_0
  - nspr=4.28=he1b5a44_0
  - nss=3.56=he751ad9_0
  - numpy=1.19.1=py37h7ea13bd_2
  - oauth2client=4.1.3=py_0
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1h=h516909a_0
  - ossuuid=1.6.2=hf484d3e_1000
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.2=py37h3340039_0
  - pandoc=2.10.1=h516909a_0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=he7ab937_1005
  - paramiko=2.7.2=pyh9f0ad1d_0
  - parso=0.7.1=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-parent=0.236=pl526_1
  - perl-uri=1.76=pl526_0
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xsloader=0.24=pl526_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.2.3=py_0
  - pixman=0.38.0=h516909a_1003
  - pkg-config=0.29.2=h516909a_1006
  - prettytable=0.7.2=py_3
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - protobuf=3.13.0=py37h3340039_0
  - psutil=5.7.2=py37h8f50634_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pulp=1.6.8=py37_1000
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pygraphviz=1.5=py37h8f50634_1002
  - pynacl=1.3.0=py37h516909a_1001
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.17.3=py37h8f50634_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=py37hc8dfbb8_1
  - python=3.7.8=h6f2ec95_1_cpython
  - python-dateutil=2.8.1=py_0
  - python-irodsclient=0.8.2=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=pyh9f0ad1d_0
  - pyyaml=5.3.1=py37h8f50634_0
  - pyzmq=19.0.2=py37hac76be4_0
  - qt=5.12.9=h1f2b2cb_0
  - qtconsole=4.7.7=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - ratelimiter=1.2.0=py37hc8dfbb8_1001
  - readline=8.0=he28a2e2_2
  - requests=2.24.0=pyh9f0ad1d_0
  - rsa=4.6=pyh9f0ad1d_0
  - s3transfer=0.3.3=py37hc8dfbb8_1
  - scikit-learn=0.23.2=py37h6785257_0
  - scipy=1.5.2=py37hb14ef9d_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37hc8dfbb8_1
  - simplejson=3.17.2=py37h8f50634_0
  - six=1.15.0=pyh9f0ad1d_0
  - slacker=0.14.0=py_0
  - smmap=3.0.4=pyh9f0ad1d_0
  - snakemake=5.24.2=0
  - snakemake-minimal=5.24.2=py_0
  - sqlite=3.33.0=h4cf870e_0
  - sra-tools=2.10.8=pl526haddd2b5_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hed695b0_0
  - toml=0.10.1=pyh9f0ad1d_0
  - toolz=0.10.0=py_0
  - toposort=1.5=py_3
  - tornado=6.0.4=py37h8f50634_1
  - traitlets=5.0.4=py_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_1
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - widgetsnbextension=3.5.1=py37hc8dfbb8_1
  - wrapt=1.12.1=py37h8f50634_1
  - xmlrunner=1.7.7=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.3.0=py37h516909a_1000
  - zeromq=4.3.2=he1b5a44_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1009
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - adjusttext==0.7.3
    - biopython==1.78
    - cycler==0.10.0
    - descartes==1.1.0
    - dms-variants==0.8.5
    - dmslogo==0.5.1
    - kiwisolver==1.2.0
    - logomaker==0.8
    - matplotlib==3.3.2
    - mizani==0.7.1
    - natsort==7.0.1
    - neutcurve==0.5.2
    - palettable==3.3.0
    - patsy==0.5.1
    - pdb-prot-align==0.5.0
    - pillow==7.2.0
    - plotnine==0.7.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - regex==2020.7.14
    - seaborn==0.11.0
    - statsmodels==0.12.0
    - svgutils==0.3.1
    - xlrd==1.2.0
prefix: /fh/fast/bloom_j/software/miniconda3/envs/SARS-CoV-2-RBD_MAP

